/**
 * web/components/connect-ibkr-form.tsx
 *
 * IBKR individual accounts do not expose a static API key. Signal Stack connects
 * to an authenticated Client Portal Gateway / secure bridge session instead.
 * The saved bridge token belongs to the user's bridge, not to IBKR.
 */

'use client';

import { useActionState, useState } from 'react';
import { saveIbkrConnectionAction, type ActionResult } from '@/app/dashboard/futures-actions';

async function wrapper(_prev: ActionResult | null, formData: FormData): Promise<ActionResult> {
  return saveIbkrConnectionAction(formData);
}

export function ConnectIbkrForm() {
  const [state, formAction, pending] = useActionState(wrapper, null);
  const [environment, setEnvironment] = useState<'paper' | 'live'>('paper');

  return (
    <section style={panel}>
      <h3 style={{ margin: 0, fontSize: 16 }}>Connect Interactive Brokers</h3>
      <p style={{ color: 'var(--muted)', marginTop: 8, fontSize: 13, lineHeight: 1.6 }}>
        IBKR does not provide a normal API key for individual accounts. Log in through
        Client Portal Gateway or IB Gateway, then connect Signal Stack to that authenticated
        session. The optional bridge token below is generated by your Signal Stack bridge —
        it is not your IBKR password and is never returned to the browser.
      </p>

      <form action={formAction} style={grid}>
        <Field label="Environment">
          <select name="environment" value={environment} onChange={(e) => setEnvironment(e.target.value as 'paper' | 'live')} style={input}>
            <option value="paper">Paper</option>
            <option value="live">Live</option>
          </select>
        </Field>

        <Field label="IBKR Account ID">
          <input name="accountId" type="text" required style={input} autoComplete="off" placeholder="U1234567" />
        </Field>

        <Field label="Gateway / Bridge URL">
          <input
            name="gatewayUrl"
            type="url"
            required
            style={input}
            autoComplete="off"
            placeholder="https://your-secure-ibkr-bridge.example.com/v1/api"
          />
        </Field>

        <Field label="Bridge Token (optional)">
          <input name="bridgeToken" type="password" style={input} autoComplete="off" placeholder="Signal Stack bridge token" />
        </Field>

        <Field label="API Client ID">
          <input name="clientId" type="number" min="0" max="31" defaultValue="7" required style={input} autoComplete="off" />
        </Field>

        <div style={{ gridColumn: '1 / -1', padding: '10px 12px', borderRadius: 6, background: 'var(--bg)', border: '1px solid var(--border)', color: 'var(--muted)', fontSize: 12, lineHeight: 1.5 }}>
          For local testing, run the scanner service and IBKR Client Portal Gateway on the same machine.
          A cloud-hosted Signal Stack deployment requires a secured bridge or tunnel because IBKR requires
          individual Client Portal Gateway calls to originate from the authenticated gateway machine.
        </div>

        <div style={{ gridColumn: '1 / -1', display: 'flex', justifyContent: 'flex-end', marginTop: 4 }}>
          <button type="submit" disabled={pending} style={{ ...btn, cursor: pending ? 'wait' : 'pointer' }}>
            {pending ? 'Saving…' : 'Save IBKR connection'}
          </button>
        </div>
      </form>

      {state && !state.ok && <div style={errBox}>{state.error}</div>}
      {state && state.ok && <div style={okBox}>IBKR gateway connection saved.</div>}
    </section>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
      <span style={{ fontSize: 12, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: '1px', fontWeight: 700 }}>{label}</span>
      {children}
    </label>
  );
}

const panel: React.CSSProperties = { background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: 10, padding: 24 };
const grid: React.CSSProperties = { marginTop: 16, display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 12 };
const input: React.CSSProperties = { padding: '10px 12px', background: 'var(--bg)', border: '1px solid var(--border)', color: 'var(--text)', borderRadius: 6, fontFamily: 'inherit', fontSize: 13 };
const btn: React.CSSProperties = { padding: '10px 24px', background: 'var(--accent)', color: '#001a33', border: 'none', borderRadius: 6, fontFamily: 'inherit', fontWeight: 700, fontSize: 13 };
const errBox: React.CSSProperties = { marginTop: 12, padding: '10px 14px', background: '#320d0d', border: '1px solid #5c1a1a', color: 'var(--bad)', borderRadius: 6, fontSize: 13 };
const okBox: React.CSSProperties = { marginTop: 12, padding: '10px 14px', background: '#0d3320', border: '1px solid #1a5c38', color: 'var(--good)', borderRadius: 6, fontSize: 13 };
